### ISSUE TITLE
Nintendo Switch Online v2.10.1 upgrade required

### ISSUE THREAD

**Issue by Div1793** [samuelthomas2774/nxapi#110]
![Screenshot 2024-07-01 232854](https://github.com/samuelthomas2774/nxapi/assets/174407026/6acba192-8caa-467f-92e6-067cd3fd00b2)
was working fine then it just started doing this

**Comment by Sentineluno** [comment]
also got this issue just now, i thought there was an update but i see nothing, hope it gets a fix soon.

**Comment by samuelthomas2774** [comment]
This is caused by repeated failed attempts to authenticate.

The actual issue here is that 2.10.0 is no longer supported and the f generation API currently does not support 2.10.1 yet.

**Comment by samuelthomas2774** [comment]
I've updated the f generation API and nxapi's remote configuration, it should work after restarting the app.
