### ISSUE TITLE
Enhancement: Add more customisation to Discord presence

### ISSUE THREAD

**Issue by Velegand** [samuelthomas2774/nxapi#13]
I would like to be able to disable the total playtime on the Discord Presence.

**Comment by samuelthomas2774** [comment]
There is actually a few options for customising Discord activities in the app, there's just no UI yet.

If you want to completely hide the play time for now you can run this in the browser window developer tools console (<kbd>Cmd</kbd>+<kbd>Opt</kbd>+<kbd>I</kbd>/<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>I</kbd>):

```js
await nxapiElectronIpc.setDiscordPresenceConfig({...await nxapiElectronIpc.getDiscordPresenceConfig(), show_play_time: 0})
```

There's a few other things I want to work on first, so it might be a while before I add these options to the app UI, but I'll leave this issue open until then.

**Comment by samuelthomas2774** [comment]
Options for customising Discord activities were added to the app in [v1.5.0](https://github.com/samuelthomas2774/nxapi/releases/tag/v1.5.0) (see #19).
