### ISSUE TITLE
Warning via CLI (Windows, Git Bash)

### ISSUE THREAD

**Issue by anthonybaldwin** [samuelthomas2774/nxapi#15]
Figured I'd mention in case others run into this and load your history w/ `unidentified-script` requests...if not just me (I started the issue before realizing it's only Git Bash). Will have to look into a possible solution later... For now, I'll just use PowerShell or Command Prompt.

----

https://github.com/samuelthomas2774/nxapi/blob/fe725f931a5cf3f1f779f78f85c20fe378d2a43c/src/cli.ts#L57-L58

----

❌ **Git Bash**:
```
$ nxapi --version
[warn] The nxapi command is not running in a terminal. If using the nxapi command in a script or other program, the NXAPI_USER_AGENT environment variable should be set. See https://gitlab.fancy.org.uk/samuel/nxapi#user-agent-strings.
1.2.0
```

✔️ **PowerShell**:
```
PS D:\> nxapi --version
1.2.0
```

✔️ **Command Prompt**:
```
D:\>nxapi --version
1.2.0
```

**Comment by samuelthomas2774** [comment]
This should happen (but also shouldn't...) when redirecting output, as `process.stdout` will be a pipe/file instead of a TTY. This shouldn't happen in an actual terminal.

It looks like this is because Git Bash doesn't actually create a Windows console, so I don't think there's any way to fix this (other than using CMD/PowerShell/WSL).

**Comment by anthonybaldwin** [comment]
>but `process.stderr` shouldn't ever be redirected, unless it's not running in a terminal.

I'll give it a go this evening if you don't beat me to it.

**Comment by samuelthomas2774** [comment]
Closing this as it's not really an issue with nxapi, but feel free to create a pull request to detect Git Bash specifically as a terminal (see the linked commit below for where this is checked).

---

For detecting a terminal while redirecting output: https://github.com/samuelthomas2774/nxapi/commit/33958618b0c5ad2ce25e4831654c93fcae12f09d changes the `process.stdout.isTTY` check to use both `stdin` and `stderr` instead, as currently there are no real uses for redirecting these streams:

```
samuel nxapi % node bin/nxapi.js --version | cat -                   
  nxapi:update git repository exists, skipping update check +0ms
1.3.0
samuel nxapi % echo | node bin/nxapi.js --version | cat -
[warn] The nxapi command is not running in a terminal. If using the nxapi command in a script or other program, the NXAPI_USER_AGENT environment variable should be set. See https://gitlab.fancy.org.uk/samuel/nxapi#user-agent-strings.
  nxapi:update git repository exists, skipping update check +0ms
1.3.0
```
