### ISSUE TITLE
error everytime i open

### ISSUE THREAD

**Issue by SucksAtstuff** [samuelthomas2774/nxapi#16]
![image_2022-07-29_171240555](https://user-images.githubusercontent.com/75032354/181790125-06b650f2-8957-4d90-81ae-167aff2b8e73.png)

it worked fine up until the update and now i get that error everytime i open the application

**Comment by samuelthomas2774** [comment]
That was quick; I was hoping Nintendo might not force updating to 2.2.0 for a while since it drops support for iOS 12-13.

---

Fixed in https://github.com/samuelthomas2774/nxapi/commit/85a91933285d5a8fc98d02c9d38e760c871d26b0. I'll try to release an update soon (my CI server isn't working, so I might just build the next release locally as this one is urgent).

I am working on a way to update the reported Coral version number without an update, safely, so this should be easier to handle in the future.

**Comment by SucksAtstuff** [comment]
so at the moment all i can do is wait for a new version?

**Comment by samuelthomas2774** [comment]
> so at the moment all i can do is wait for a new version?

Yes, unless you want to try building the app from source. I'll add a comment here once I've released the next version.

**Comment by SucksAtstuff** [comment]
id rather wait than trying to do that

**Comment by samuelthomas2774** [comment]
I've set up a mirror on gitlab.com and *exactly the same job* works there... You can download preview builds from there now:

- macOS and Linux: https://gitlab.com/samuelthomas2774/nxapi/-/jobs/artifacts/main/browse/app?job=build
- Windows: https://gitlab.com/samuelthomas2774/nxapi/-/jobs/artifacts/main/browse/app?job=build-windows

**Comment by SucksAtstuff** [comment]
so that does work?

**Comment by samuelthomas2774** [comment]
It should do.

I've not tested the Windows build properly as I mostly use macOS but it includes all the same changes, including updating the version number it reports to Nintendo.

**Comment by SucksAtstuff** [comment]
it didnt give me and error when i opened so i think it works Thx

**Comment by pattax** [comment]
Fixed the error for me as well but the discord status doesnt update at all in that build (windows)

**Comment by samuelthomas2774** [comment]
> Fixed the error for me as well but the discord status doesnt update at all in that build (windows)

@pattax Is it connecting to Discord ok? You should see your username when playing a game:

<img width="384" alt="Screenshot 2022-07-30 at 15 49 04 2" src="https://user-images.githubusercontent.com/8474065/181919775-4c1fc3bf-b058-4609-a914-bab609226bee.png">

**Comment by pattax** [comment]
Fixed it by removing/adding my accounts, not sure what went wrong there

**Comment by samuelthomas2774** [comment]
Closing as [v1.3.0](https://github.com/samuelthomas2774/nxapi/releases/tag/v1.3.0) has now been released.

(If you're using a preview build you'll still see a new update available.)
