### ISSUE TITLE
Potentially misplaced titles

### ISSUE THREAD

**Issue by Rexogamer** [samuelthomas2774/nxapi#22]
Shouldn't the Let's Go title data (currently listed [here](https://github.com/samuelthomas2774/nxapi/blob/56a991b03b4399eae474f927c7e405fcd4168dc0/src/discord/titles/nintendo.ts#L211-L232)) be in [the Pokémon file](https://github.com/samuelthomas2774/nxapi/blob/56a991b03b4399eae474f927c7e405fcd4168dc0/src/discord/titles/the-pokémon-company.ts)?

**Comment by samuelthomas2774** [comment]
The Discord title configuration is sorted by the publisher as listed on the Nintendo eShop, so these are correct.

Links to the Australia Nintendo eShop (as it just uses the standard eShop page):

- https://ec.nintendo.com/apps/010003f003a34000/AU - Pokémon: Let's Go, Pikachu!, Nintendo
- https://ec.nintendo.com/apps/0100939011ed4000/AU - Pokémon UNITE, The Pokémon Company

**Comment by Rexogamer** [comment]
Fair enough, albeit a bit surprising - just wanted to make sure ^^
