### ISSUE TITLE
Pokemon Scarlet/Violet

### ISSUE THREAD

**Issue by Peri0dic** [samuelthomas2774/nxapi#31]
### Title name

Pokémon Scarlet / Pokémon Violet

### Publisher

Nintendo

### Title IDs

0100A3D008C5C000 Pokémon Scarlet
01008F6008C5E000 Pokémon Violet

### Other information

Didn't want to make two issues so I just included both titles in the title name section but obviously they are separate.

### Review checklist

- [X] No other open issues related to this title exist (if any issues do exist, add a comment/reaction to those instead of opening a new issue)
- [X] I am requesting a custom Discord application for this title - this title is a very popular game and/or has high ratings, is currently available for purchase (or will be soon) in most Nintendo eShop regions, and it would be useful for a number of users to have it's own Discord application (I don't have any strict guidelines for which titles should have custom Discord applications - tick if you think the title should have it's own Discord application - I just want to keep the list short so I don't have to create 100s of Discord applications)

**Comment by samuelthomas2774** [comment]
Added in [v1.6.0](https://github.com/samuelthomas2774/nxapi/releases/tag/v1.6.0) (https://github.com/samuelthomas2774/nxapi/commit/a8f665953ba734b4390ad29b71fc69d94239187a).
