### ISSUE TITLE
Samsung Android device support/application

### ISSUE THREAD

**Issue by VincentJoshuaET** [samuelthomas2774/nxapi#32]
Samsung and Discord has a partnership so that Galaxy devices will show the game being currently played via Samsung's Game Launcher app. See this link for more information: https://support.discord.com/hc/en-us/articles/360031924632-Samsung-Integration-FAQ

Do you think it's possible to take advantage of this feature to implement nxapi for Android? This will be for Samsung devices only, but they're the most popular Android device manufacturer so this will still be very useful to many.

![image](https://user-images.githubusercontent.com/19756326/203904611-5c957d18-fc98-4309-ac54-461ef4251fe0.png)

![image](https://support.discord.com/hc/article_attachments/360036968892/5.png)

![image](https://support.discord.com/hc/article_attachments/360036969072/6.png)

![image](https://support.discord.com/hc/article_attachments/360036969192/8.png)

**Comment by FieryFlames** [comment]
I don't think this would be possible. As far as I know, game launcher just uses the app's name from the manifest, so if nxapi were to somehow work through this, it would need to have multiple installed apps for different games which is very impractical.

**Comment by AAGaming00** [comment]
This also only works on an approved whitelist of games IIRC

**Comment by VincentJoshuaET** [comment]
> This also only works on an approved whitelist of games IIRC

https://www.reddit.com/r/discordapp/comments/d2mv0o/comment/ezx15id

Based on most experiences it works on every game.

I'd actually be okay with individual apps for this. We don't need to download every app for each game, just the ones we have/we want to show the status.

I think Tachiyomi uses individual APKs for each source, it would be just easy to press a single button to download an APK especially if it's just small because it's not the actual game

**Comment by FieryFlames** [comment]
While using multiple apps would be possible to show presence using game launcher, I don't think it would make sense for this to go into nxapi, or to do all the work to get this working.

**Comment by samuelthomas2774** [comment]
nxapi is primarily just a tool for accessing Nintendo Switch services. Discord presence is a feature of nxapi because it can be fully automated using data from Nintendo's API. Because a mobile application would require manual data entry (opening specific apps depending on the title you're playing) I don't think it would make sense to create a mobile version of nxapi.
