### ISSUE TITLE
403 forbidden error SplatNet3Monitor

### ISSUE THREAD

**Issue by queenbiscuit311** [samuelthomas2774/nxapi#34]
Immediately when chill season started the splatoon 3 rich presence monitor broke entirely and keeps recieving 403 errors. Not sure if it's an app being outdated issue or if nintendo broke it.

**Comment by samuelthomas2774** [comment]
Nintendo started requiring SplatNet 3 v2.0.0 which caused this to stop working (`403 Forbidden` from SplatNet 3 means `ERROR_OBSOLETE_VERSION`). I updated the remote configuration data so it should start working after restarting the app.
