### ISSUE TITLE
Error in external monitor SplatNet3Monitor

### ISSUE THREAD

**Issue by MCJlol** [samuelthomas2774/nxapi#45]
<img width="416" alt="Screenshot_20221218_111112" src="https://user-images.githubusercontent.com/91104933/208352446-1cfee8eb-51c2-46c6-b6ca-ffc53eab2219.png">

**Comment by MCJlol** [comment]
If I keep on pressing "Retry" it comes up again (this is enhanced Discord Rich Presence)

**Comment by samuelthomas2774** [comment]
Duplicate of #39.

Fixed in [v1.6.0](https://github.com/samuelthomas2774/nxapi/releases/tag/v1.6.0).
