### ISSUE TITLE
The SSL/TLS problem during the adding user processes

### ISSUE THREAD

**Issue by hilot06** [samuelthomas2774/nxapi#47]
It's throw error when adding user if the user name of PC was percent decoded.
The error message is like this:

> Error adding account
> FetchError$1: request to https://accounts.nintendo.com/connect/1.0.0/api/session_token
> failed, reason: unable to get local issuer certificate
>     at ClientRequest. <anonymous> (file:///C:/Users/`username`/AppData/Local/Programs/nx...:11)
>     at ClientRequest.emit (node:events:539:35)
>     at TLSSocket.socketErrorListener (node:_http_client:454:9)
>     at TLSSocket.emit (node:events:527:28)
>     at emitErrorNT (node:events:527:28)
>     at emitErrorCloseNT (node:internal/streams/destroy:122:3)
>     at process.processTicksAndRejections (node:internal/process/task_queues:83:21)

I founded, when I try adding user with the English PC user name (e.g.`hilot`) I successfully added user, but when I try with the Japanese name (e.g.`ひろっと`or`山田`) I couldn't add user.
I'm not good at English, so if you didn't catch the meanings or situations I'm very sorry.
Thank you

**Comment by techy804** [comment]
I have the same error but I only have Latin alphanumeric characters in mine, so I doubt it's just Japanese letters that are causing the issue.

**Comment by hilot06** [comment]
Hmm... I searched with `unable to get local issuer certificate`, and many pages said it's just the issue of SSL/TLS with Git.

> The common cause behind “Cause of SSL Certificate Problem: Unable to get Local Issuer Certificate” is an error that causes misconfiguration while sending all the root and intermediate certimficates to the webserver correctly at the time of SSL/TLS communication between the client and the server.
> 
> In some cases, when you’re using client SSL certificates, when you make a request to a secure HTTPS source, you have to share an SSL certificate to verify your identity. As such, if you come across the “SSL certificate problem: unable to get local issuer certificate” error, it’s an indication that the root certificates on the system are not working correctly.
> 
> From [this page](https://cheapsslsecurity.com/blog/ssl-certificate-problem-unable-to-get-local-issuer-certificate/)

So I changed the issue name to this. (...or shouldn't I change the name so often? I don't know the manner of GitHub...)

**Comment by hilot06** [comment]
I get it. This is because I have set Firewall as not normally.
It's my problem...
