### ISSUE TITLE
Monster hunter Rise

### ISSUE THREAD

**Issue by Peri0dic** [samuelthomas2774/nxapi#5]
### Title name

Monster Hunter Rise

### Publisher

CAPCOM

### Title IDs

0100B04011742000 Monster Hunter Rise
010093a01305c000 Monster Hunter Rise Demo Version2
0100db001724e000 Monster Hunter Rise: Sunbreak Demo

(This is the titleID for the Asia/JP version, I wasn't sure if you wanted the JP/ENG title so I included the JP titles just incase, but its in the same order as the US/EU version (Main game, Demo, and sunbreak demo).
0100559011740000 モンスターハンターライズ
0100bef013050000 モンスターハンターライズ DEMO
01000ee01724c000 モンスターハンターライズ：サンブレイク DEMO

### Other information

I think they just replaced demo version 1 with 2 so the titleID stayed the same. Also this is my first time submitting a game so I was not familiar with the process of gathering titleID's and the regions of games but I think the game only has a NA/EU version and an Asia version, excluding China but I doubt this app has any Chinese users. Let me know if I made any mistakes.

### Review checklist

- [x] No other open issues related to this title exist (if any issues do exist, add a comment/reaction to those instead of opening a new issue)
- [X] I am requesting a custom Discord application for this title - this title is a very popular game and/or has high ratings, is currently available for purchase (or will be soon) in most Nintendo eShop regions, and it would be useful for a number of users to have it's own Discord application (I don't have any strict guidelines for which titles should have custom Discord applications - tick if you think the title should have it's own Discord application - I just want to keep the list short so I don't have to create 100s of Discord applications)

**Comment by samuelthomas2774** [comment]
This will be included in the next release. (macOS and Linux app users can download preview builds from GitLab: https://gitlab.fancy.org.uk/samuel/nxapi/-/jobs/artifacts/main/browse/app?job=build.)

@Peri0dic Thanks for including all the title IDs. 👍
