### ISSUE TITLE
Pokemon Unite

### ISSUE THREAD

**Issue by Guille91** [samuelthomas2774/nxapi#6]
### Title name

Pokémon UNITE

### Publisher

The Pokémon Company

### Title IDs

0100939011ed4000 Pokémon UNITE

### Other information

From what I could find, apparently there's only one global version, therefore just one ID.

### Review checklist

- [X] No other open issues related to this title exist (if any issues do exist, add a comment/reaction to those instead of opening a new issue)
- [X] I am requesting a custom Discord application for this title - this title is a very popular game and/or has high ratings, is currently available for purchase (or will be soon) in most Nintendo eShop regions, and it would be useful for a number of users to have it's own Discord application (I don't have any strict guidelines for which titles should have custom Discord applications - tick if you think the title should have it's own Discord application - I just want to keep the list short so I don't have to create 100s of Discord applications)

**Comment by samuelthomas2774** [comment]
Added in [v1.2.0](https://github.com/samuelthomas2774/nxapi/releases/tag/v1.2.0).
