### ISSUE TITLE
Rich presence literally does not work on Linux

### ISSUE THREAD

**Issue by BFCE** [samuelthomas2774/nxapi#69]
Tried using the appImage version and the deb version, neither actually show rich presence on discord. Another project, NSO-RPC (https://github.com/MCMi460/NSO-RPC), does work without issues, so it appears to be a problem with this project only. It is worth mentioning, that I (like many others) use the flatpak version of discord, and that may be related to the issue.

**Comment by AAGaming00** [comment]
probably flatpak issue, rich presence works fine for me on Linux

**Comment by BFCE** [comment]
> probably flatpak issue, rich presence works fine for me on Linux

Probably right, but still needs to be addressed. Other apps are able to work fine with flatpak

**Comment by BFCE** [comment]
workaround: 
```
mkdir -p ~/.config/user-tmpfiles.d
echo 'L %t/discord-ipc-0 - - - - app/com.discordapp.Discord/discord-ipc-0' > ~/.config/user-tmpfiles.d/discord-rpc.conf
systemctl --user enable --now systemd-tmpfiles-setup.service
```
